# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20170524_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pizza',
        ),
        migrations.AddField(
            model_name='comment',
            name='pizza',
            field=models.ManyToManyField(related_name='comments', to='pizza.Pizza'),
        ),
    ]
