# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20170524_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pizza',
        ),
        migrations.AddField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizza.Pizza'),
        ),
    ]
